# Generated by Django 5.0.1 on 2026-03-27 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Especes'), ('mtn_momo', 'MTN MoMo'), ('orange_money', 'Orange Money'), ('bank_transfer', 'Virement bancaire')], max_length=20)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('payment_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('confirmed', 'Confirme'), ('voided', 'Annule')], default='confirmed', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('subtotal', models.IntegerField(default=0)),
                ('discount_percent', models.IntegerField(default=0)),
                ('discount_amount', models.IntegerField(default=0)),
                ('discount_reason', models.TextField(blank=True, default='')),
                ('total', models.IntegerField(default=0)),
                ('paid_amount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiellement paye'), ('paid', 'Paye'), ('cancelled', 'Annule')], default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
