# Generated by Django 5.0.1 on 2026-03-27 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_initial'),
        ('clinics', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='visit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='visits.visit'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='visit_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='visits.visitservice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['clinic', 'status'], name='invoices_clinic__649317_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['clinic', 'patient'], name='invoices_clinic__35e370_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['clinic', 'invoice_number'], name='invoices_clinic__a49d70_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['clinic', 'invoice'], name='payments_clinic__1f4c95_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['clinic', 'payment_method'], name='payments_clinic__71b3b0_idx'),
        ),
    ]
