# Generated by Django 5.0.1 on 2026-02-15 06:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                ("phone_primary", models.CharField(max_length=20)),
                (
                    "phone_secondary",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("invoice_prefix", models.CharField(default="INV-", max_length=10)),
                (
                    "invoice_numbering",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Reset"),
                            ("monthly", "Monthly"),
                            ("continuous", "Continuous"),
                        ],
                        default="continuous",
                        max_length=20,
                    ),
                ),
                ("invoice_footer", models.TextField(blank=True, default="")),
                ("cash_threshold", models.IntegerField(default=500)),
                (
                    "mtn_momo_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "orange_money_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bank_account",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "clinics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("consultation", "Consultation"),
                            ("laboratory", "Laboratoire"),
                            ("pharmacy", "Pharmacie"),
                            ("care", "Soins"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["clinic", "category"],
                        name="services_clinic__1acf20_idx",
                    ),
                    models.Index(
                        fields=["clinic", "is_active", "is_deleted"],
                        name="services_clinic__81f197_idx",
                    ),
                ],
                "unique_together": {("clinic", "code")},
            },
        ),
    ]
