# Generated by Django 5.0.1 on 2026-03-27 04:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_type', models.CharField(choices=[('walkin', 'Walk-in'), ('appointment', 'Rendez-vous'), ('followup', 'Suivi'), ('emergency', 'Urgence')], default='walkin', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('invoiced', 'Facture'), ('completed', 'Termine'), ('cancelled', 'Annule')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_visits', to=settings.AUTH_USER_MODEL)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinics.clinic')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='patients.patient')),
            ],
            options={
                'db_table': 'visits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.IntegerField(help_text='Snapshot of service price at time of addition')),
                ('price_override', models.IntegerField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_visit_services', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_services', to='clinics.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='visits.visit')),
            ],
            options={
                'db_table': 'visit_services',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clinic', 'status'], name='visits_clinic__81b884_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clinic', 'patient'], name='visits_clinic__79611d_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['clinic', '-created_at'], name='visits_clinic__88cd26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitservice',
            unique_together={('visit', 'service')},
        ),
    ]
